### ISSUE TITLE
Rozwój pagination

### ISSUE THREAD

**Issue by tlekenta** [tlekenta/kwejk#4]
- ładowanie obrazków w zależności od aktualnej strony (obecnie nie zależnie od strony ładują się zawsze te same obrazki)

- CSS

**Comment by mndzielski** [comment]
Dobra to będzie może po 3 obrazki na strone, tak żeby tych 5 wystarczyło na więcej niż jedną stronę

**Comment by kubazrb** [comment]
no ja w starym projekcie mam funkcje, co wyciaga z bazy obrazki w zaleznosci od strony

**Comment by kubazrb** [comment]
Trzeba zrobić tak, żeby obrazki się sortowały od najnowszego (dodałem datę). Bo jak narazie po dodaniu obrazka leci on na dół, a nie na górę strony.
