### ISSUE TITLE
Obsługa topek

### ISSUE THREAD

**Issue by tlekenta** [tlekenta/kwejk#5]
- Top miesiąca

- Top roku

Trzeba dodać odpowiednie metody w PictureService, PictureRepository i PictureController. Formatek nie trzeba będzie zmieniać.

**Comment by kubazrb** [comment]
już są, zrobiłem nowy html z include gallery, żeby można było dodać napis i jakieś gówno inne jak ktoś chce

**Comment by kubazrb** [comment]
nie działa tylko punktowanie w topkach i profilu (narazie nie wiem dlaczego, jak ktos ma czas to prosze bardzo)
